#!/usr/bin/env python3
"""Generate exact CRT constants for the Ozaki-II style emulation (src/oz_consts.h).

For s moduli p_1..p_s (pairwise coprime, <= 256) with P = prod p_l:
  q_l  = (P/p_l)^{-1} mod p_l          (folded into the residues of A)
  w_l  = P/p_l, split exactly as  w_l = wh_l + wm_l + wl_l  with
         wh_l a multiple of 2^G with < 2^40 significant bits relative to 2^G,
         wm_l a multiple of 2^(G-40) below 2^G, wl_l the (rounded) rest,
  P    split the same way.
Given y_l = (q_l * Cbar) mod p_l in [0, p_l), the centred integer is
  Cbar = (sum y_l wh_l - r Ph) + (sum y_l wm_l - r Pm) + (sum y_l wl_l - r Pl),
  r = round(sum y_l / p_l).
This script also checks every split exactly with Python integers.
"""
from fractions import Fraction
import math, sys

MODULI = [256, 255, 253, 251, 247, 241, 239, 233, 229, 227, 223, 217, 211, 199, 197, 193, 191, 181, 179, 173]
SMAX = len(MODULI)

for i in range(SMAX):
    for j in range(i + 1, SMAX):
        assert math.gcd(MODULI[i], MODULI[j]) == 1


def split3(x, G):
    """x (int) = h + m + l, h multiple of 2^G, m multiple of 2^(G-40), |m| < 2^G; l rounded to double."""
    h = (x >> G) << G
    rem = x - h
    gm = G - 40
    m = (rem >> gm) << gm if gm > 0 else rem
    l = rem - m
    assert float(h) == h and float(m) == m  # exactly representable
    return h, m, l


def main(out):
    lines = ["// Generated by tools/gen_oz_consts.py -- do not edit.", "#pragma once", f"#define OZ_SMAX {SMAX}",
             "static const int oz_mod[OZ_SMAX] = {" + ", ".join(map(str, MODULI)) + "};", ""]
    lines.append("typedef struct { double log2P; double Ph, Pm, Pl; int q[OZ_SMAX]; double invp[OZ_SMAX];"
                 " double wh[OZ_SMAX], wm[OZ_SMAX], wl[OZ_SMAX]; } oz_const_t;")
    lines.append("static const oz_const_t oz_const[OZ_SMAX + 1] = {")
    for s in range(0, SMAX + 1):
        if s < 2:
            lines.append("  {0},")
            continue
        ps = MODULI[:s]
        P = math.prod(ps)
        G = max(P.bit_length() - 40, 0)
        Ph, Pm, Pl = split3(P, G)
        q, wh, wm, wl = [], [], [], []
        for p in ps:
            w = P // p
            qi = pow(w % p, -1, p)
            assert (qi * w) % p == 1
            h, m_, l = split3(w, G)
            assert h + m_ + l == w and h % (1 << G) == 0 and h < (1 << (G + 41))
            q.append(qi); wh.append(h); wm.append(m_); wl.append(l)
        # exactness of the high sum: y_l < 256, s terms, all multiples of 2^G
        assert sum(255 * h for h in wh) < (1 << (G + 53))
        fmt = lambda v: repr(float(v))
        lines.append(f"  {{ {math.log2(P)!r}, {fmt(Ph)}, {fmt(Pm)}, {fmt(Pl)},")
        lines.append("    {" + ", ".join(map(str, q)) + "},")
        lines.append("    {" + ", ".join(repr(1.0 / p) for p in ps) + "},")
        lines.append("    {" + ", ".join(fmt(v) for v in wh) + "},")
        lines.append("    {" + ", ".join(fmt(v) for v in wm) + "},")
        lines.append("    {" + ", ".join(fmt(v) for v in wl) + "} },")
    lines.append("};")
    open(out, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "src/oz_consts.h")
